### ISSUE TITLE
Strange description

### ISSUE THREAD

**Issue by EJUNBLACK** [EJUNBLACK/ForApp#1]
Please check your last commit because it is so strange to include string..

**Comment by CoolMan1000** [comment]
OMG, It is your code... check by yourself

**Comment by EJUNBLACK** [comment]
Which one?

**Comment by EJUNBLACK** [comment]
This one 1a0d1814945647083bb74603b2ef21e6091c98cd

**Comment by EJUNBLACK** [comment]
YEAB.. It is resolved, already.

**Comment by CoolMan1000** [comment]
Thank you~
